### ISSUE TITLE
Wish: Contribution trampoline widget

### ISSUE THREAD

**Issue by raulk** [libp2p/docs#10]
As people consume libp2p documentation, we should leverage the opportunity to get them to contribute to libp2p.

**How to achieve this?** By reducing friction between the time that people think “wow, this is interesting” (while reading), and they find a meaningful thing to contribute to.

**Concept:** a context-sensitive “widget” that integrates with Github in each section of our docs, and pulls a list of issues relevant to the content being viewed, tabbed by language so that people can jump straight into making contributions.

This requires annotating each page with metadata to link it to the relevant repos, and using the Github Search API to pull the data in.

So imagine you’re reading all about relays, and just at the bottom of the page (or elsewhere) there's a wishlist of features pulled from go-libp2p-circuit, js-libp2p-circuit, etc. to get you into hacking mode.

When people select a language tab, we should remember their language preference throughout the navigation.

Consider integrating with [SourceCred](https://sourcecred.io/) for a gamified experience.

**Comment by DannyS03** [comment]
Closing in favor of: https://github.com/libp2p/docs/discussions/208.
