### ISSUE TITLE
Libp2p documentation

### ISSUE THREAD

**Issue by milexm** [libp2p/docs#105]
Started reading the libp2p documentation: https://docs.libp2p.io/introduction/what-is-libp2p/. Just scratching the surface. 
At first glance, I would say that some good diagrams would be very helpful. For example, what is the libp2p diagram that is equivalent to the OSI model diagram? 

![image](https://user-images.githubusercontent.com/14791422/131264033-0bb5c10a-e912-46f1-a386-7cec4edbdc48.png)

Thanks

**Comment by mxinden** [comment]
:wave: Hi @milexm,

>  At first glance, I would say that some good diagrams would be very helpful. For example, what is the libp2p diagram that is equivalent to the OSI model diagram?

The [ResNetLab on Tour](https://research.protocol.ai/tutorials/resnetlab-on-tour/modular-p2p-stack/) module on lbp2p by @adlrocha explains libp2p's position in the OSI model.

As always, especially around docs, contributions of any form are very welcome.

**Comment by MarcoPolo** [comment]
Thanks all. Closing this issue since I think we've answered the original question and the issue title is really general. Feel free to open a new specific issue.
