### ISSUE TITLE
Can I  use PHP or C ++ language to  wirte code for libp2p? 

### ISSUE THREAD

**Issue by Rock-liyi** [libp2p/docs#107]
I am Rock , a  PHP and C++ programmer,   i would like to contribute code for libp2p recently, but  only good  at PHP and C++,  
sometimes  I would   wirte  Golang  code ，but  did  not doing  very well ， so I hope that  build a new libp2p project  for  PHP  or C++ .

Thank you !

**Comment by mxinden** [comment]
There is a C++ implementation: https://github.com/libp2p/cpp-libp2p

I am sure the folks maintaining it would appreciate any help.
