### ISSUE TITLE
Review "What is libp2p?" and update timestamp

### ISSUE THREAD

**Issue by NiloCK** [libp2p/docs#111]
From https://github.com/libp2p/docs/blob/master/content/introduction/what-is-libp2p.md:

> Here I’ll try to briefly outline the main problem areas that are addressed by libp2p today (__early 2019__).

(emphasis added)

... does not inspire HUGE confidence in the reader. The doc seems reasonable to me, but I'm not yet well informed on the project.

Consider:
- reviewing the doc and updating the timestamp to `CURRENTDATE`
- dropping most of that paragraph. Probably this project is mature enough now that its goals / capabilities aren't so rapidly changing that it's needed. Something like

>Here I’ll try to briefly outline the main problem areas that are addressed by libp2p. We’ll do our best to keep this section up-to-date, but if you notice something missing or have other ideas for improving this documentation, please [reach out to let us know](https://github.com/libp2p/docs/issues/).

is probably reasonable.

**Comment by mxinden** [comment]
Good catch. Suggestion looks good to me. Can you propose a pull request @NiloCK. Contributions would be more than welcome.

**Comment by NiloCK** [comment]
done at #113 .

Should I feel free to open minor drive-by PRs like this one on other small docs issues without first creating issues?

**Comment by mxinden** [comment]
> Should I feel free to open minor drive-by PRs like this one on other small docs issues without first creating issues?

Either first creating an issue, or opening a pull request right away is fine by me. These drive-by contributions are very much appreciated!
