### ISSUE TITLE
Missing "ctx" definition in "Getting Started with go-libp2p" tutorial

### ISSUE THREAD

**Issue by sa8** [libp2p/docs#139]
#### Location

The issue is located here: https://docs.libp2p.io/tutorials/getting-started/go/ in the very last example "Run the ping protocol."

#### Description

`ctx` is used in the code without being defined hence the code does not build.

**Comment by sa8** [comment]
Sure, PR created.

**Comment by marten-seemann** [comment]
> Note that this example is not supposed to build without modification anyway. There's a ... in the import statement and in the code. We also don't import all the standard library packages that are used.

And I was wrong here. The last but one uses the `...`, but the last one is supposed to build.
