### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by h1z1** [libp2p/docs#149]
https://github.com/libp2p/docs/pull/133 added a link to discord that points to a channel directly.  Either the permissions on the server are incorrect (you can block unregistered users), or the link should be an invite for the server.

This is the [invite](https://discord.com/invite/KKucsCpZmY)  link to discord in other parts of ipfs.

As per the server [this](https://discord.gg/ipfs) might be better.

The channel link points to libp2p-dev on that server.

**Comment by mxinden** [comment]
Not sure what the current process is. @BigLep @johnnymatthews can you take a look?
