### ISSUE TITLE
Guide for how to respond to resource exhaustion attacks

### ISSUE THREAD

**Issue by BigLep** [libp2p/docs#153]
## Done Criteria
We have a document we can point libp2p operators to in defense of or response to various resource exhaustion attacks (DoS, eclipse).

## Why Important
Especially in the heat of battle, every minute reducing response/mitigation times can be significant.  Having suggestions/steps prethought outside the fog of war will provide better suggestions in a quicker period of time.

## User/customer
Anyone operating a libp2p node in production.  This could range from desktop users to system administrators.  

## Notes
1. This should range from the full set of knobs available to an operator from implementation-specific items like go-libp2p resource manager config changes to more "nuclear" options like operating system iptable/firewall rules.
2. Anything developed in https://github.com/libp2p/go-libp2p-resource-manager/issues/29 should be included.
3. It's true system admins won't need coaching on operating system defense mechanisms, but this is relevant to surface for less-trained users.
4. An important aspect of this document layout is account for the OS items that are implementation agnostic to the implementation specific items.  It's possible that implementation-specific docs live in the implementation repos and are linked from this docs.libp2p.io page.
5. Once https://github.com/libp2p/docs/issues/158 is done, we should link to it as well.

**Comment by MarcoPolo** [comment]
I assigned this to myself but I'd love pair on this with someone from fil-infra/bifrost.

**Comment by p-shahi** [comment]
Done in v0.21.0 and deployed https://docs.libp2p.io/reference/dos-mitigation/
