### ISSUE TITLE
Remove secio from docs

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/docs#157]
This is deprecated

**Comment by mxinden** [comment]
Folks decided for a deprecation notice back then.

https://github.com/libp2p/docs/pull/130

I am fine either way, though might be good referencing it somewhere for folks to be able to understand the history of the protocol.

**Comment by mxinden** [comment]
Also see https://github.com/libp2p/specs/pull/308.

**Comment by marten-seemann** [comment]
I think we should remove it. No need to confuse people with ancient protocols that are not in use any more. At this point, it's very unlikely that people will stumble over secio any more.
