### ISSUE TITLE
Guide for libp2p node monitoring

### ISSUE THREAD

**Issue by BigLep** [libp2p/docs#158]
## Done Criteria

There is a easily discoverable way for a libp2p node operator to find the monitoring options available to them for the libp2p implementation they are using (e.g., new docs section/page at https://docs.libp2p.io/monitoring).

## Why Important
 
libp2p implementations have various ways to view node health.  This information is usually buried within language-specific docs, which can be harder to discover.

## Notes

This page is expected to be minimal, mostly providing links to the relevant documentation for specific implementations for things like "how to enable Granafa dashboards".

There should likely be some linking from the docs generated from https://github.com/libp2p/docs/issues/153 as well.

**Comment by mxinden** [comment]
The rust-libp2p metrics module with an example as well as a Grafana dashboard can be found here:

https://github.com/libp2p/rust-libp2p/tree/master/misc/metrics

**Comment by BigLep** [comment]
@mxinden : are you suggesting our new docs page should link to https://github.com/libp2p/rust-libp2p/tree/master/misc/metrics ?  

I think it's great that it shows what an example dashboard can look like by linking to https://kademlia-exporter.max-inden.de/d/Pfr0Fj6Mk/rust-libp2p .   Other questions/observations though:
1. Is it clear for users how they turn this on themselves?
2. Do we also want to link to https://docs.rs/libp2p/0.46.1/libp2p/metrics/index.html ?
3. https://docs.rs/libp2p/0.46.1/libp2p/metrics/index.html doesn't surface the example dashboard
4. https://docs.rs/libp2p/0.46.1/libp2p/metrics/index.html references an "examples" directory, but doesn't link to it.

**Comment by mxinden** [comment]
> are you suggesting our new docs page should link to https://github.com/libp2p/rust-libp2p/tree/master/misc/metrics ?

Yes. It links to the dashboard and the examples directory.

> Is it clear for users how they turn this on themselves?

That is my intuition, given that there is an `examples` directory.

> Do we also want to link to https://docs.rs/libp2p/0.46.1/libp2p/metrics/index.html ?

I am fine with it, though I am not sure how much help the docs are.

> https://docs.rs/libp2p/0.46.1/libp2p/metrics/index.html references an "examples" directory, but doesn't link to it.

It is a convention to have an `examples` directory at the root of the crate (aka package), thus Rust users will know where to find it.

**Comment by BigLep** [comment]
This is being handled in https://github.com/libp2p/docs/pull/160

**Comment by p-shahi** [comment]
Parts related to resource mgmt are addressed in https://docs.libp2p.io/reference/dos-mitigation/#monitoring-your-application

We have a metrics effort in go-libp2p started, we can include this as a part of that. Therefore closing in favor of libp2p/go-libp2p#1356
