### ISSUE TITLE
Add DHT to concepts

### ISSUE THREAD

**Issue by momack2** [libp2p/docs#183]
https://docs.libp2p.io/concepts/

add DHT

**Comment by DannyS03** [comment]
Already tracked in https://github.com/libp2p/docs/issues/35

**Comment by DannyS03** [comment]
Reference added to the launchpad DHT page [here](https://github.com/libp2p/docs/pull/220) and lives [here](https://docs.libp2p.io/concepts/fundamentals/dht/). We're considering adding a dedicated page eventually.
