### ISSUE TITLE
Populate secure communication section: Noise & TLS

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/docs#19]
We should cover how libp2p's support for encrypted communication works, from the negotiation process (link to multistream concept article) to the specific implementations (~secio~, tls, etc).

## Done Criteria
- [x] Enhance secure comm overview
- [x] Populate Noise doc
- [x] Populate TLS doc

## Why Important
No explicit material on the supported secure channels in libp2p.

**Comment by MousyBusiness** [comment]
> We should cover how libp2p's support for encrypted communication works, from the negotiation process (link to multistream concept article) to the specific implementations (secio, tls, etc).

Is there information on this anywhere, I'm really stuggling to piece together how libp2p works in production from these examples

**Comment by frink** [comment]
Shouldn't this now be about noise instead of secio?

**Comment by mxinden** [comment]
> Shouldn't this now be about noise instead of secio?

Correct. Updated the title.

Would you be interested in contributing such doc @frink? I am happy to help.

**Comment by frink** [comment]
Sorry I don't have time right now.

**Comment by Amdela79** [comment]
collectibles":{"favorites":{}},"engine":{"backgroundState":{"AccountTrackerController":{"accounts":{"0xF64D769b3a91534c7b873e387b0Fed0933bcc20B":{"balance":"0x0"}}},"AddressBookController":{"addressBook":{}},"TokenListController":{"tokenList":{"0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f":{"address":"0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f","symbol":"SNX","decimals":18,"name":"Synthetix Network Token","iconUrl":"https://assets.coingecko.com/coins/images/3406/large/SNX.png","aggregators":["aave","bancor","cmc","cryptocom","coinGecko","oneInch","paraswap","pmm","synthetix","zapper","zerion","zeroEx"],"occurrences":12},"0x1f9840a85d5af5bf1d1762f925bdaddc4201f984":{"address":"0x1f9840a85d5af5bf1d1762f925bdaddc4201f984","symbol":"UNI","decimals":18,"name":"Uniswap","iconUrl":"https://images.prismic.io/token-price-prod/d0352dd9-5de8-4633-839d-bc3422c44d9c_UNI%404x.png","aggregators":["aave","bancor","cmc","cryptocom","coinGecko","oneInch","paraswap","pmm","zapper","zerion","zeroEx
