### ISSUE TITLE
Update diagrams for Hole Punching article

### ISSUE THREAD

**Issue by p-shahi** [libp2p/docs#207]
We currently use UML sequence diagrams in the Hole Punching documentation:
![image](https://user-images.githubusercontent.com/50885601/196305455-7c5a6d3f-977d-4885-8298-d56c82a6d0c7.png)

We need to replace these with updated diagrams when they become available.

---
See the discussion here: https://github.com/libp2p/docs/pull/200/files#r980363822

**Comment by DannyS03** [comment]
Given the nature of this issue in comparison to https://github.com/libp2p/docs/issues/206, we can track the scope of this issue in 206 as the diagrams here would, in part, also be used for other docs in the NAT section, and we are tracking all the other diagram updates in 206.

Going forward, we should follow the libp2p blog post approach and include new diagrams and graphics as part of the change request. However, given that the open PRs (many documenting protocols and process) have been hanging for some time, my approach was to get those merged and add the diagrams shortly after to limit the friction.

In the near term where there is little to no "doc debt", we'll make it a habit to request diagrams as documents are created and ship them together.
