### ISSUE TITLE
Upgrade to a new site theme

### ISSUE THREAD

**Issue by p-shahi** [libp2p/docs#217]
## Motivation
The current libp2p docs site uses Hugo Learn, a theme that is outdated and inhibits better ways of organizing content.
Thanks to more modern themes, other docs site in the ecosystem ([IPFS](https://docs.ipfs.tech/), [Testground](https://docs.testground.ai/), [Filecoin](https://docs.filecoin.io/about-filecoin/what-is-filecoin/), etc.) are better composed, have better UI/UX, and offer a better reading and browsing experience.

## Why Important
[Described in greater detail here](https://github.com/libp2p/docs/discussions/210#discussioncomment-3930443) but a new theme will help better organize site subdirectories (like enabling Guides/Examples/Tutorials to have its own section), be more flexible for new content/content types, offer a better UI/UX for readers (better page navigation, improved interface), and be more presentable in general.

## Done Criteria

- [x] New theme is agreed on and deployed

---

**Design changes are orthogonal and out of scope for migrating to a new theme.**
For design updates see: https://github.com/libp2p/docs/issues/206

**Comment by p-shahi** [comment]
Hugo themes to consider: https://www.notion.so/pl-strflt/Docs-430f9ad3ae4f48a9ae54f4008377a93f

**Comment by DannyS03** [comment]
With all things considered, the Doks theme is the most reasonable.
- The docs team is migrating the IPFS and IPLD docs to use Doks.
- Launchpad is also using Doks.
- It is the most maintained theme.
- It standardizes the docs infrastructure.
- Doks also allows us to accomplish the ideas & proposals we have raised.

I am still in favor of creating a book-like resource, but we can make the main priority.

**Comment by DannyS03** [comment]
@p-shahi we can migrate to the new theme before the end of the week. I believe it is reasonable to pursue by involving the docs team more than the stewards based on usage of the Doks theme already, consensus by the docs team, and the migration not necessarily impacting additional next steps raised [here](https://github.com/libp2p/docs/discussions/210). However, input is always encouraged @BigLep, @mxinden, @marten-seemann, @MarcoPolo.

**Comment by mxinden** [comment]
> However, input is always encouraged @mxinden 

No opinion on a theme for docs.libp2p.io.
