### ISSUE TITLE
Link to libp2p connectivity site

### ISSUE THREAD

**Issue by p-shahi** [libp2p/docs#218]
## Done Criteria

- [ ] We have a link to the new `connectivity.libp2p.io` site

---

## Open Question

Should it be added as a it's own section (on the left nav bar), under Reference, or linked elsewhere?
@DannyS03 @marten-seemann your preference?

**Comment by DannyS03** [comment]
We can add to both (left nav bar and reference section), similar to specs and also mention it on the transport index. I think it would be good for exposure.
