### ISSUE TITLE
bug: pages don't link to the next page in sections

### ISSUE THREAD

**Issue by p-shahi** [libp2p/docs#224]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/50885601/202537671-81b967ea-9320-4726-b3a2-fc80a43c5506.png">

The provided screenshot shows an example of incorrect next and previous links on a docs page. This issue occurs on all pages.

Here, the "Fundamentals/Overview" page's next link should direct to "Fundamentals/Addressing" and it's previous link should direct to "Introduction/What is libp2p"

**Comment by johnnymatthews** [comment]
The next and previous buttons are managed by the `weight` variable within each `.md` file. So in this example, these should be the weights of each page:

| Page title | Weight | 
| --- | --- |
| What is libp2p | 10 |
| Overview | 20 |
| Addressing | 30 |
| The DHT | 40 |
| Protocols | 50 |
| Peers | 60 |

etc.
