### ISSUE TITLE
bug: Table of Contents missing for some pages

### ISSUE THREAD

**Issue by p-shahi** [libp2p/docs#226]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/50885601/202538882-195478c2-8405-42f0-87e8-cd8f95f4a3c5.png">

Some pages don't correctly render their sections in the "On This Page" Table of Contents
https://docs.libp2p.io/concepts/nat/circuit-relay/ in contrast with https://docs.libp2p.io/concepts/nat/hole-punching/

**Comment by DannyS03** [comment]
Ah, this is because of the heading level being used, which in the case of circuit relay is 4 (i.e. ####). Let's update the titles.
