### ISSUE TITLE
Add additional QUIC muxer to QUIC transport doc

### ISSUE THREAD

**Issue by DannyS03** [libp2p/docs#242]
## Done Criteria
- ~[x] Create an overview for "QUIC Native Stream Multiplexing" section~

EDIT: Add a section further describing QUIC steam muxing.

## Why Important
- ~Page was created as a placeholder and requires additional material.~
- ~The doc serves a better purpose in being about native stream muxers (in general).~

EDIT: Decided to just include this as part of the QUIC transport doc.

**Comment by marten-seemann** [comment]
Do you want to explain in detail how QUIC does stream multiplexing? I’m wondering if the libp2p docs are the right place for that, this seems very QUIC specific.

**Comment by DannyS03** [comment]
Right along the same lines. Think it would be useful to have material that introduces having a transport with a native stream muxer, how it works/how it works in libp2p.
