### ISSUE TITLE
broken links?

### ISSUE THREAD

**Issue by jennijuju** [libp2p/docs#255]
google leads me to 

![image](https://user-images.githubusercontent.com/42981373/203768079-6bc21d84-67fc-4422-b48a-1232ebb015b8.png)

but then click on the link  https://docs.libp2p.io/concepts/addressing/ 
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/42981373/203768051-9f49115d-b060-41e2-bb9e-478d7c72c3cd.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/42981373/203768217-fde317dc-b865-4d9d-af14-1d6dea951797.png">

**Comment by DannyS03** [comment]
https://github.com/libp2p/docs/pull/254
