### ISSUE TITLE
Improve Examples section

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/docs#29]
The current examples section just links to external sources for go, js and rust.

I think there's a big opportunity to take those external examples and rework them a bit, pull them into the site, and use them as teaching tools to walk people through libp2p use cases.

I think that keeping the examples in their own repos will probably work best, since that's the easiest place to keep them up-to-date and integrated with CI.

My tentative plan is to clone the example repos as part of the build process for this site, run them through some formatting, and embed the result into the site.

For this to work well, some work needs to be done on the example repos so that they all have enough narrative & framing around them, and I need to develop the formatting / build process.

**Comment by tristanisham** [comment]
@yusefnapora [I created a pull for the Go getting started example](https://github.com/libp2p/docs/pull/138). In its current state, it won't compile. There's no mention of the necessary declaration of `ctx` as seen in the last two code snippets of the document. 
```go
 // The context governs the lifetime of the libp2p node.
// Cancelling it will stop the the host.
ctx, cancel := context.WithCancel(context.Background())
defer cancel()
```

**Comment by p-shahi** [comment]
Reach out to other implementations (Python, Nim, Zig, etc) to be included in examples page. Will close the child tickets in favor of this one.

**Comment by DannyS03** [comment]
After having touched on this issue (and idea) a few times in the latter half of 2022, the preference among the stewards is to keep the examples in their respective repos.

We also have a general "[Guides](https://docs.libp2p.io/guides/getting-started/go/)" section now that provides guides to get started with libp2p, and it will continue to refer to the examples in each repo (for example, as mentioned [here](https://github.com/libp2p/docs/issues/247#issuecomment-1368758838)). Implementations that do not have a getting started guide will be added shortly.

As a result, let's close this and revisit if necessary.
