### ISSUE TITLE
Populate "WebRTC Browser-to-Browser" in transport/webrtc

### ISSUE THREAD

**Issue by p-shahi** [libp2p/docs#302]
## Context

The libp2p maintainers have continued specifying the WebRTC specification and are adding support for browser-to-browser connectivity:

- The `Working Draft` version of the specification is in progress: https://github.com/libp2p/specs/pull/497.
- Per the working draft, three libp2p implementations are estimated to add support during Q2 2023 ([go-libp2p](https://github.com/libp2p/go-libp2p/blob/master/ROADMAP.md#end-of-q4-december), [js-libp2p](https://github.com/libp2p/js-libp2p/blob/master/ROADMAP.md#end-of-q4-december), and [rust-libp2p](https://github.com/libp2p/rust-libp2p/blob/master/ROADMAP.md#webrtc-support-browser-to-server)).
- [WebRTC interoperability testing](https://github.com/libp2p/test-plans/blob/master/ROADMAP.md#mid-q4-november) across implementations is also started mid Q4.

## Done Criteria

- [ ] Populate the "Browser-to-Browser" section in the WebRTC transport document.
- [ ] Audit and edit the original WebRTC transport document to ensure the general content does not revolve browser-to-server.
- [ ] Add a short comparison sub-section comparing the differences in connectivity
 
## Why Important

- Expanding the ways libp2p enables connectivity (into browser connectivity) is a primary goal of the libp2p project, WebRTC is centre to that. As we finish specification and implementation, we need corresponding documentation for the transport and it's use-cases.
- This continues the transport documentation for WebRTC started by #211.

**Comment by DannyS03** [comment]
Marking as blocked until https://github.com/libp2p/docs/pull/264 is pushed.
