### ISSUE TITLE
Internal Markdown links not working

### ISSUE THREAD

**Issue by leovct** [libp2p/docs#306]
The link to transport protocols is broken on the [intro page](https://docs.libp2p.io/concepts/introduction/overview/#why-libp2p).
It redirects to this page which doesn't exist on `ipfs`: https://docs.libp2p.io/concepts/introduction/transports/overview.md.
I get the following error on Chrome: `ipfs resolve -r /ipfs/bafybeifxgfygni2u2wq2d73ws43hblb3mvmiplap5vfyesa5pwjsl2ur6a/concepts/introduction/transports/overview.md: no link named "transports" under QmYNJvZRXGPzPGQMYoujvnUzRLYVBfGdeo5HoeoSY652sp`

**Comment by DannyS03** [comment]
Thanks @leovct

**Comment by DannyS03** [comment]
Issue still persists

**Comment by DannyS03** [comment]
Not the only page or link either.

**Comment by DannyS03** [comment]
I believe it is because of the project root and needing to use the relative path, updating now
