### ISSUE TITLE
Audit all links

### ISSUE THREAD

**Issue by DannyS03** [libp2p/docs#309]
## Context

- Follows https://github.com/libp2p/docs/issues/306 to take the time to check all links and references.
- This should be addressed once majority of the MVP doc changes are shipped (i.e. most of the open PRs are merged).

**Comment by p-shahi** [comment]
You might be able to use https://wellshapedwords.com/posts/linkchecking/how-i-check-links/ or https://validator.w3.org/checklink?uri=https%3A%2F%2Fdocs.libp2p.io%2Fconcepts&hide_type=all&depth=&check=Check

**Comment by DannyS03** [comment]
cheers @p-shahi

@ElPaisano is also working on linters that we we're planning to add to the libp2p docs
