### ISSUE TITLE
add `/ipfs/0.1.0` to protocols page

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/docs#323]
I see the subject protocol used in the code (like here https://github.com/libp2p/universal-connectivity/issues/66), but didn't find an explanation in the docs (so far, perhaps I missed it).

Would be great if there was an addition to this page:

https://docs.libp2p.io/concepts/fundamentals/protocols/#core-libp2p-protocols 

Also, is there a complete listing to all the protocol strings somewhere?

Does this just mean "use all protocols starting with `/ipfs/**/**` ?

**Comment by p-shahi** [comment]
ref: https://github.com/libp2p/go-libp2p/issues/2294

**Comment by 2color** [comment]
Closing this issue, given that this is a protocol specific parameter. I also agree this is confusing, but this can likely just be resolved with a comment in the rust-libp2p implementation indicating that it's purely metadata.
