### ISSUE TITLE
js-libp2p ping-pong - TypeError: node.ping is not a function

### ISSUE THREAD

**Issue by stefan1010** [libp2p/docs#324]
Receiving: TypeError: node.ping is not a function

Running on:
` "dependencies": {
    "@chainsafe/libp2p-noise": "^12.0.0",
    "@libp2p/mplex": "^8.0.3",
    "@libp2p/tcp": "^7.0.1",
    "libp2p": "^0.45.1",
    "multiaddr": "^10.0.1"
  }`

Maybe implementation has changed?

**Comment by maschad** [comment]
Correct we recently integrated the use of optional services, and so the [_ping method_ is on the `PingService`](https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#configuring-protocol-name). 

Thanks for catching this! We do need to update the [getting started docs](https://github.com/libp2p/docs/blob/d53ebe15ff036466b892429b6ab2b23140e6d983/content/guides/getting-started/javascript.md?plain=1#L225). Would you be able to open a PR?

**Comment by stefan1010** [comment]
Would love to, but from the docs I can't figure out how to use the PingService.

From configuring it as a service on the node, I would expect it to be callable from `node.services.ping`. But that gives me `..not a function` as well.

Not configuring it and directly calling `pingService(ma)` is the only working solution I found, but it's not a method on the pingService as you mentioned, so this is confusing me. I also don't see a way to get the latency, as part of the getting started docs.

**Comment by maschad** [comment]
I would need to see your configuration but [here's an example](https://github.com/libp2p/js-libp2p/blob/5ce17d1224ed6fe7edf18225d8d9177534fef6bf/test/ping/ping.node.ts#L60) of how it's called on the ping service i.e. essentially `node.services.ping.ping(ma)` . I hope that clears things up.

**Comment by stefan1010** [comment]
Receiving 403 permission denied when I try to push my branch.

Sorry, I dont know how to create the PR. Would be my first one on github.

**Comment by maschad** [comment]
Sure no worries, you may want to read through the [Github docs on creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).  Once you've done that then I would suggest taking a look at our section on [contributing content](https://github.com/libp2p/docs#contributing-content)

**Comment by stefan1010** [comment]
Opened this PR:
https://github.com/libp2p/docs/pull/325

Not sure how to link it to this issue.
Not sure if the PR follows appropriate conventions.
Any hints and advice appreciated.
