### ISSUE TITLE
Pull JS examples into docs site

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/docs#36]
This is part of #29, specific to the [js examples](https://github.com/libp2p/js-libp2p/tree/master/examples)

The overall goal is to pull each of these into the docs site, ideally by automatically extracting the narrative text directly from the README files (with edits so things make sense).

- [ ] Transports
- [ ] Protocol and Stream Muxing
- [ ] Encrypted Communications
- [ ] Discovery Mechanisms
- [ ] Peer and Content Routing
- [ ] PubSub
- [ ] NAT Traversal
- [ ] Running libp2p in the Browser
- [ ] The standard echo net example with libp2p
- [ ] A simple chat app with libp2p

**Comment by p-shahi** [comment]
https://github.com/libp2p/docs/issues/38#issuecomment-1228641402
