### ISSUE TITLE
Question in Stream Multiplexing

### ISSUE THREAD

**Issue by junekhan** [libp2p/docs#364]
[This doc](https://github.com/libp2p/docs/blob/master/content/concepts/multiplex/overview.md#overview) says `Two libp2p peers may have a single TCP connection and use different port numbers to distinguish streams.`, but to my prior knowledge, a TCP connection involves a pair of ports on source and destination devices, respectively, so ` to distinguish streams with different port numbers over a single TCP connection` really confuses me. It sounds like a TCP connection can have as many ports involved in libp2p implementation. Could someone please help me on this?

**Comment by Stebalien** [comment]
Yes, that's just incorrect. Could you make a PR to remove that sentence?
