### ISSUE TITLE
Pull Go examples into docs site

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/docs#37]
This covers the go part of #29 

The idea is to pull the examples from https://github.com/libp2p/go-libp2p-examples into the docs site, ideally using an automated process to pull in the narrative and code samples from the example READMEs. May take some rewriting / tweaking of the readmes

- [ ] The libp2p 'host'
- [ ] Building an http proxy with libp2p
- [ ] An echo host
- [ ] Multicodecs with protobufs
- [ ] P2P chat application
- [ ] P2P chat application w/ rendezvous peer discovery
- [ ] P2P chat application with peer discovery using mdns

**Comment by p-shahi** [comment]
https://github.com/libp2p/docs/issues/38#issuecomment-1228641402
