### ISSUE TITLE
Relays and AutoRelay

### ISSUE THREAD

**Issue by ghost** [libp2p/docs#4]
We should address this topic somewhere in the docs, probably as part of a larger discussion of NATed hosts.  Points to cover:

1.  What are Relay nodes?  (Servers operated by PL that NAT'd hosts can connect to directly to discover peers.  Explain that *all* traffic from nodes using a relay will pass through the relay, which is expensive and expected to be slower than direct connections.  We should also explain to folks that if you use this, you're relying on a piece of centralized infrastructure and all the limitations that come with that...)

2.  How do I use relay nodes in my code?  How can a user tell whether his traffic is going through a relay node?  (I believe the answer to the first one is that it's just a flag in the go-libp2p Host constructor.  We should show a code example, including how to catch errors if relay nodes are unavailable for some reason.  Also, I believe only go-libp2p supports this right now; should make that clear.  On the second one, I don't know.  If there's not a way, we should log an issue with whoever is working on diagnostic tooling for libp2p.)

3.  Other NAT hole punching.  The whole reason for relay nodes is to help developers whose users have NAT'd hosts, like PCs on a home router.  We should roll this in to a larger discussion of NAT'd hosts, e.g., current status of uPnP to open ports on the router, current status of STUN/ICE (not available afaik), etc.

**Comment by elahn** [comment]
I found the Circuit Relay > [Relay Addresses](https://docs.libp2p.io/concepts/circuit-relay/#relay-addresses) section confusing. Should some instances of `QmAlice` actually be `QmBob`?

**Comment by jacobheun** [comment]
> I found the Circuit Relay > Relay Addresses section confusing. Should some instances of QmAlice actually be QmBob?

It's correct, but I think things could be clearer. There's really no reason to even mention `QmBob` because they're the dialing node and we don't really care what their ID is and I think it just adds to the confusion. 

Perhaps it would be better to simply take the recommended address structure `/ip4/7.7.7.7/tcp/55555/p2p/QmRelay/p2p-circuit/p2p/QmAlice` and break down the address components.

**Comment by p-shahi** [comment]
close this in favor of: https://github.com/libp2p/docs/issues/172 and https://github.com/libp2p/docs/issues/171
