### ISSUE TITLE
Tutorial proposal: Implementing a Protocol

### ISSUE THREAD

**Issue by lmars** [libp2p/docs#46]
This is a proposal for a tutorial to follow the current ["Getting Started"](https://docs.libp2p.io/tutorials/getting-started/) tutorials based on what I would have found useful as I've been getting to know libp2p in the last week or so.

The tutorial would be called "Implementing a Protocol" and would cover:

- Defining a protocol ID and setting a stream handler
- Reading and writing protocol data
- Defining a set of structured messages that make up the protocol
- Encoding / decoding protocol messages
- Handling different types of messages
- Handling an async request / response flow
- Handling protocol upgrades (i.e. version bumps, semver matching)

Rather than making up a protocol, I suggest using an existing, simple protocol that's easy to understand and doesn't distract from the point of the tutorial, perhaps [JSON-RPC](https://www.jsonrpc.org/specification) over libp2p?

@yusefnapora WDYT? I'd be happy to draft a Go version of this if you think it would be useful? I always like sharing my learning experience to make it easier for others 😄

**Comment by yusefnapora** [comment]
That sounds like a great plan. I can work on the JS side while you're working on Go, if you like. This sounds like fun 😄

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/docs/issues/120
