### ISSUE TITLE
link from libp2p.io to docs.libp2p.io

### ISSUE THREAD

**Issue by ghost** [libp2p/docs#47]
We should update https://libp2p.io/ to have a `Documentation` link (pointing to docs.libp2p.io) to the right of `Specifications`.  Or wherever in that top nav bar makes the most sense.

I'll let you figure this one out, @yusefnapora .  Not too urgent.

**Comment by tesla809** [comment]
Yea, I just noticed this. Might be a quick fix with a decent return vs work ratio.

**Comment by DannyS03** [comment]
this now exists, closing
