### ISSUE TITLE
Spelling error in glossary of libp2p docs: "transport" spelled "tranport" in switch definition.

### ISSUE THREAD

**Issue by tesla809** [libp2p/docs#50]
In definition of Switch, the word transport is incorrect. It is spelled tranport and its corresponding link is broken. 

Shouldn't it be spelled: transport and the link to the transport definition in the glossary.

See:
https://docs.libp2p.io/reference/glossary/#switch

**Comment by yusefnapora** [comment]
Thank you! Sorry about the delay in fixing it up :)
