### ISSUE TITLE
Broken link in Getting Started JS tutorial

### ISSUE THREAD

**Issue by tesla809** [libp2p/docs#52]
The second note section within the getting started JS tutorial has a broken link. The link on **async/waterfall** which leads to **https://caolan.github.io/async/docs.html#waterfall** results in 404 error from Github.

Link to tutorial: (https://docs.libp2p.io/tutorials/getting-started/javascript/)

The note is:
_Because generating the key pair requires some computation, PeerInfo.create is an asynchronous operation. libp2p uses node-style callbacks for most asynchronous operations, and real-world code and more complex examples will often use helpers like **async/waterfall** to compose chains of async operations. Since this is a fairly simple example, we’re just going to use the callbacks as-is and chain them together the “old fashioned way”._

**Comment by jchris** [comment]
This paragraph is no longer in the tutorial. We can close this issue
