### ISSUE TITLE
Missing module.export code in P2PNode initial setup in JS getting started tutorial

### ISSUE THREAD

**Issue by tesla809** [libp2p/docs#53]
In initial setup of P2PNode, there module.exports code to export the module. For experienced node devs, this may not be an issue and the code may be implied. However, for those with less experience, they may be thrown off by the nebulous error message of "TypeError: P2PNode is not a constructor". 

```
const Libp2p = require('libp2p')
const TCP = require('libp2p-tcp')

const defaultsDeep = require('@nodeutils/defaults-deep')

const DEFAULT_OPTS = {
  modules: {
    transport: [
      TCP
    ]
  }
}

class P2PNode extends Libp2p {
  constructor (opts) {
    super(defaultsDeep(opts, DEFAULT_OPTS))
  }
}
// currently, no module.exports code here
/*
needs this addition
module.exports = { 
  P2PNode
};

*/

```

**Comment by p-shahi** [comment]
Need to check with current js-libp2p before closing

**Comment by DannyS03** [comment]
It seems the tutorial previously used a class method to define the node but now does not. Can close.
