### ISSUE TITLE
Missing import of peer-id in example code for JS getting started tutorial

### ISSUE THREAD

**Issue by tesla809** [libp2p/docs#54]
Inside the [getting started JS tutoria](https://docs.libp2p.io/tutorials/getting-started/javascript/)l, there is a code snippet for `pingRemotePeer()` which refers to using:`PeerId.createFromB58String()`. However, there is not mention of importing it prior to its use.

The code snippet needs to mention that we should add peer-id before creating the pingRemotePeer() function.

This can be done in the snippet where the docs say: 
"To do so, we’ll need to add a couple things to src/index.js. First, require the process module so we can get the command line arguments:"
`const process = require('process')`

Then we can add some quick information about installing and adding peer-id, as well as explaining its use.
```
npm i peer-id
const PeerId = require('peer-id')
```
It would be nice to have some quick comments or clarification on why the PeerId.createFromB58String() method is used in the code. Also nice would be a quick sentence on why use base58 in general. [Is due to the same reason that it was used in Bitcoin?](https://en.wikipedia.org/wiki/Base58l)

```
function pingRemotePeer(localPeer) {
  if (process.argv.length < 3) {
    return console.log('no remote peer address given, skipping ping')
  }
  const remoteAddr = multiaddr(process.argv[2])

  // Convert the multiaddress into a PeerInfo object
  const peerId = PeerId.createFromB58String(remoteAddr.getPeerId()) <<< ?
  const remotePeerInfo = new PeerInfo(peerId)
  remotePeerInfo.multiaddrs.add(remoteAddr)

  console.log('pinging remote peer at ', remoteAddr.toString())
  localPeer.ping(remotePeerInfo, (err, time) => {
    if (err) {
      return console.error('error pinging: ', err)
    }
    console.log(`pinged ${remoteAddr.toString()} in ${time}ms`)
  })
}
```

**Comment by jchris** [comment]
This looks like it is out of date (no use of peer-id in the tutorial). We can close.
