### ISSUE TITLE
Broken link to protocol negotiation in Transport Concepts docs

### ISSUE THREAD

**Issue by tesla809** [libp2p/docs#56]
Inside the [Transport docs](https://docs.libp2p.io/concepts/transport/) in Concepts section, the following sentence has a broken link:

> The libp2p component responsible for managing the transports is called the switch, which also coordinates [protocol negotiation](https://docs.libp2p.io/concepts/protocol-negotiation), stream multiplexing, establishing secure communication and other forms of “connection upgrading”.

The protocol negotiation link goes to: https://docs.libp2p.io/concepts/protocol-negotiation

Which returns the message:
`ipfs resolve -r /ipns/docs.libp2p.io/concepts/protocol-negotiation: no link named "protocol-negotiation" under QmcuoK1NLYx6n438xBvxqH1nfnj7LTdSQxKcKCX2wM9x6n`

**Comment by DannyS03** [comment]
updated
