### ISSUE TITLE
Broken link related to "Go's Host Interface" in Protocol Concepts docs

### ISSUE THREAD

**Issue by tesla809** [libp2p/docs#59]
In the [handler functions portion of the Protocol docs](https://docs.libp2p.io/concepts/protocols/#handler-functions) under Concepts, the following sentence has a broken link:

> To accept connections, a libp2p application will register handler functions for protocols using their protocol id with the switch (aka “swarm”), or a higher level interface such as [go’s Host interface](https://github.com/libp2p/go-libp2p-host/blob/master/host.go).

The go host interface link goes to: https://github.com/libp2p/go-libp2p-host/blob/master/host.go

Which returns a 404 error from Github.

**Comment by FlorianRuen** [comment]
Should link to https://github.com/libp2p/go-libp2p-core/blob/master/host/host.go
