### ISSUE TITLE
Placing Protocols as first doc in Concepts section

### ISSUE THREAD

**Issue by tesla809** [libp2p/docs#60]
Just a thought: Would placing the [Protocol docs](https://docs.libp2p.io/concepts/protocols/) first make the [Concepts section](https://docs.libp2p.io/concepts/) flow better? That way developers are introduced to the concept of networking protocols which is the foundation of the entire stack.

Thoughts?

**Comment by p-shahi** [comment]
In a discussion with @marten-seemann and @DannyS03 we agree that the current Transport first works fine. We can revisit this if you have a stronger opinion @tesla809
