### ISSUE TITLE
PubSub Gossip concept does not match Go implementation

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/docs#66]
The snazzy looking pubsub concept documentation describes Gossipsub's gossip as emitting to 6 peers every 1 second. https://github.com/libp2p/docs/pull/64/files#diff-c5421c96c419b40b9ccba140bf7376c4R211-R214

However, in the Go implementation that's not the case. Instead it emits to 0-6 peers every 1 second, depending on if the randomly selected peers are ones that are already in the mesh. https://github.com/libp2p/go-libp2p-pubsub/blob/master/gossipsub.go#L513-L520

I'm not sure which one of these is the bug, but I recall @vyzo mentioning that this was done intentionally in the Go gossipsub implementation to cause less messages to be propagated from smaller degree nodes.

@raulk @vyzo thoughts?

**Comment by aschmahmann** [comment]
It was agreed that this was an implementation bug which is now fixed.

**Comment by vyzo** [comment]
It was not a bug; just a different approach that was trying to minimize the emitted gossip!
