### ISSUE TITLE
Broken link to the discussion about the renaming Swarm -> Switch

### ISSUE THREAD

**Issue by ackintosh** [libp2p/docs#72]
https://docs.libp2p.io/reference/glossary/#swarm
> See [the discussion about the name change](https://github.com/libp2p/js-libp2p-switch/issues/40) for context.

**Comment by jchris** [comment]
It looks like the repo with the discussion has been deprecated. I'll create a PR removing the discussion link.

**Comment by jchris** [comment]
fixed in #129
