### ISSUE TITLE
TODO link broken on "What is libp2p?" page

### ISSUE THREAD

**Issue by JoeThielen** [libp2p/docs#75]
On this page: https://docs.libp2p.io/introduction/what-is-libp2p/ in the _What problems can libp2p solve_ section, the _many projects_ and _reach out to let us know_ links both point towards a _TODO_ link ( https://docs.libp2p.io/TODO ), which, when clicked, produces this output:

`ipfs resolve -r /ipns/docs.libp2p.io/TODO: no link named "TODO" under QmeNJdQTHY55sEanTBsG9SS5c7v7fjgNPBkT6QXt489eiK`

**Comment by DannyS03** [comment]
addressed in the referenced PR
