### ISSUE TITLE
Add style guide / conventions

### ISSUE THREAD

**Issue by ghost** [libp2p/docs#8]
Not urgent, but at some point other people are going to start contributing to this documentation.  If we have a set of writing conventions we want them to follow, it's much easier to lay down some ground rules in advance and then politely say in review "Can you revise this per our style guidelines [link]."

I would backlog this until we start getting a few outside contributions.  That'll give a sense of what kind of weird (to us, but normal in the contributor's mind) types of writing we get.

**Comment by yusefnapora** [comment]
The ipfs/community repo has a [docs styleguide](https://github.com/ipfs/community/blob/master/DOCS_STYLEGUIDE.md) we can look at adopting and tweaking

**Comment by DannyS03** [comment]
Closing in favor of: https://github.com/libp2p/docs/discussions/208.
