### ISSUE TITLE
Broken link Configure libp2p "one for node.js" "one for the browser"

### ISSUE THREAD

**Issue by haydenyoung** [libp2p/docs#80]
Thanks for the great documentation.

https://docs.libp2p.io/tutorials/getting-started/javascript/#configure-libp2p

The links "one for node.js" and "one for the browser" do not link to an existing Github page.

https://github.com/ipfs/js-ipfs/tree/master/src/core/runtime/libp2p-nodejs.js

https://github.com/ipfs/js-ipfs/tree/master/src/core/runtime/libp2p-browser.js

Guessing their new location is:

https://github.com/ipfs/js-ipfs/blob/10e8682e44ed06fdcad849b7cb7e6a38dbd9ba49/packages/ipfs/src/core/runtime/libp2p-nodejs.js

https://github.com/ipfs/js-ipfs/blob/10e8682e44ed06fdcad849b7cb7e6a38dbd9ba49/packages/ipfs/src/core/runtime/libp2p-browser.js

**Comment by jacobheun** [comment]
Yes those are the correct new links. js-ipfs recently consolidated several of its packages, which looks to have broke these. Would you mind submitting a PR with the new links?

We are planning to improve configuration and have defaults available directly in js-libp2p in the future, https://github.com/libp2p/js-libp2p/issues/576, which will help us mitigate the broken references.
